server:
  port: 80
spring:
  application:
    name: mscloud-consumer-order
eureka:
  client:
    register-with-eureka: true
    service-url:
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: consumer80
    prefer-ip-address: true
